export enum TokenTag {
  whitespace,
  lineBreak,
  comment,
  identifier,
  integerLiteral,
  floatingPointLiteral,
  stringLiteral,
  booleanLiteral,
  nilLiteral,
  operator,
  dotOperator,
  leftParenthesis,
  rightParenthesis,
  leftSquareBracket,
  rightSquareBracket,
  leftCurlyBracket,
  rightCurlyBracket,
  comma,
  colon,
  semicolon,
  assignment,
  at,
  numberSign,
  keyword,

  placeholder,
}